Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -116,7 +116,7 @@ jobs:
             echo "Validating if files are in LedgerX token list:"
             echo
             awk '{print $2}' "HEAD.diff" | sort | awk 'match($0, /mappings\/[0-9a-f]+\.json/) { print substr( $0, RSTART+9, RLENGTH-14 )}' \
-                | xargs -I{} bash -c 'if ! grep -q "{}" "../ledger/tokenRegistry/top100JsonList_ep321-337.json"; then echo "WARNING subject on Ledger Top 100: mappings/{}.json"; echo "::warning file=mappings/{}.json::Metadata is part of LedgerX Top 100 token list"; echo "status=failure" >> $GITHUB_OUTPUT; else echo "mappings/{}.json not on LedgerX token list"; echo "status=success" >> $GITHUB_OUTPUT; fi'
+                | xargs -I{} bash -c 'if ! grep -q "{}" "../ledger/tokenRegistry/top100JsonList_ep321-337.json"; then echo "::warning file=mappings/{}.json::Metadata mappings/{}.json is part of LedgerX Top 100 token list"; echo "status=failure" >> $GITHUB_OUTPUT; else echo "mappings/{}.json not on LedgerX token list"; echo "status=success" >> $GITHUB_OUTPUT; fi'
             echo
 
       - name: Has been minted check
